---
name: fake-name
resource_pools:

- name: coreNode
  network: default
  size: 13
  stemcell:
    name: fake-stemcell-name-0
    version: latest
  cloud_properties:
    Bosh_ip: 10.10.10.3
    StartCpus:  4
    MaxMemory:  8192
    HourlyBillingFlag: true
    Datacenter: fake-name
    PrimaryNetworkComponent: fake-id
    PrimaryBackendNetworkComponent: fake-id
    VmNamePrefix:  fake
    EphemeralDiskSize: 25

- name: coreNode-bm
  network: default
  size: 1
  stemcell:
    name: fake-stemcell-name-1
    version: latest
  cloud_properties:
    bosh_ip: 10.10.10.4
    datacenter: fake-datacenter-name
    name_prefix: baremetal01
    server_spec:
      package: 123
      server: 123
      ram: 123
      disk0: 12345
      port_speed: 12345
      public_vlan_id: 12345
      private_vlan_id: 12345
      hourly: false
    baremetal: true
    bm_stemcell: fake-stemcell
    bm_netboot_image: fake-netbootImage