---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/bosh-lite-ci

inputs:
  - name: stemcell-version
  - name: bosh-softlayer-tools
outputs:
  - name: build
run:
  path: bosh-softlayer-tools/ci/tasks/build-stemcell-fake.sh
