---
platform: linux
image_resource:
  type: docker-image
  source: 
    repository: python

inputs:
- name: deploy-artifacts
- name: bosh-softlayer-tools

outputs:
- name: cli-vm-info

run:
  path: bosh-softlayer-tools/ci/tasks/create-env-automation/setup-cli-env.sh

params:
  SL_USERNAME:          replace-me
  SL_API_KEY:           replace-me




