---
platform: linux
image: docker:///boshcpi/azure-cpi-release

inputs:
- name: director-artifacts
- name: bosh-softlayer-tools
- name: bosh-cli-v2

outputs:
- name: cli-vm-info

run:
  path: bosh-softlayer-tools/ci/tasks/create-env-automation/setup-cli-env.sh

params:
  SL_USERNAME:          replace-me
  SL_API_KEY:           replace-me
