---
platform: linux
image: docker:///boshcpi/azure-cpi-release

inputs:
- name: director-artifacts
- name: bosh-softlayer-tools

run:
  path: bosh-softlayer-tools/ci/tasks/create-env-automation/update-dns.sh

outputs:
- name: cf-info

