---
platform: linux
image: docker:///boshcpi/azure-cpi-release

inputs:
- name: bosh-softlayer-tools
- name: cf-app

run:
  path: bosh-softlayer-tools/ci/tasks/create-env-automation/verify-cf.sh

params:
  CF_API: 			replace-me
  CF_USERNAME: 		replace-me
  CF_PASSWORD: 		replace-me
  APP_API: 			replace-me