---
platform: linux
image: docker:///cloudfoundry/bosh-lite-ci

inputs:
  - name: bosh-softlayer-stemcells
    path: gopath/src/github.com/maximilien/bosh-softlayer-stemcells
  - name: version

run:
  path: gopath/src/github.com/maximilien/bosh-softlayer-stemcells/bin/build