---
resources:
- name: bosh-softlayer-stemcells
  type: git
  source:
    uri: git@github.com:maximilien/bosh-softlayer-stemcells.git
    branch: concourse
    private_key: {{private-repo-key}}
- name: softlayer-go
  type: git
  source:
    uri: git@github.com:maximilien/softlayer-go.git
    branch: concourse
    private_key: {{private-repo-key}}
- name: bosh-softlayer-cpi
  type: git
  source:
    uri: git@github.com:maximilien/bosh-softlayer-cpi.git
    branch: concourse
    private_key: {{private-repo-key}}

jobs:
- name: sl-go-unit
  plan:
  - aggregate:
    - get: bosh-softlayer-stemcells
    - get: softlayer-go
      trigger: true
  - task: unit
    file: bosh-softlayer-stemcells/ci/softlayer-go-unit.yml
    config:
      params:
        SL_USERNAME: fake-username
        SL_API_KEY: fake-api-key
- name: cpi-unit
  plan:
  - aggregate:
    - get: bosh-softlayer-stemcells
    - get: bosh-softlayer-cpi
      trigger: true
    - get: softlayer-go
  - task: unit
    file: bosh-softlayer-stemcells/ci/bosh-softlayer-cpi-unit.yml
    config:
      params:
        SL_USERNAME: fake-username
        SL_API_KEY: fake-api-key
- name: cpi-build
  plan:
  - aggregate:
    - get: bosh-softlayer-stemcells
    - get: bosh-softlayer-cpi
      trigger: true
    - get: softlayer-go
  - task: build
    file: bosh-softlayer-stemcells/ci/bosh-softlayer-cpi-build.yml
    config:
      params:
        SL_USERNAME: fake-username
        SL_API_KEY: fake-api-key
